name: Bug report
description: Create a report to help us improve ORSEE
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or log output
      description: If applicable, add screenshots or log output to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: solution_proposal
    attributes:
      label: Solution proposal
      description: Did you already find a solution to the problem, or do you have an idea how the problem might be solved?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Technical details (please complete where potentially relevant)

  - type: input
    id: orsee_version
    attributes:
      label: ORSEE version
      placeholder: e.g. 4.1.3
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System ORSEE is running on
      placeholder: e.g. Ubuntu 22.04

  - type: input
    id: php_version
    attributes:
      label: PHP version
      placeholder: e.g. 8.2.15
    validations:
      required: true

  - type: input
    id: mysql_version
    attributes:
      label: MySQL / MariaDB version
      placeholder: e.g. MariaDB 10.6

  - type: input
    id: browser
    attributes:
      label: Browser used to access ORSEE / Desktop or Mobile
      placeholder: e.g. Chrome 122 (Desktop)

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
