name: Question
description: Do you have a question about ORSEE (that is neither about a bug nor a feature request)?
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: A clear and concise description of what you would like to know / achieve.
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried so far?
      description: Describe what you already attempted.
      placeholder: |
        e.g. I checked the documentation, searched existing issues, modified config.php, etc.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Technical details (please add if potentially relevant)

  - type: input
    id: orsee_version
    attributes:
      label: ORSEE version
      placeholder: e.g. 4.1.3

  - type: input
    id: os
    attributes:
      label: Operating system ORSEE is running on
      placeholder: e.g. Ubuntu 22.04

  - type: input
    id: php_version
    attributes:
      label: PHP version
      placeholder: e.g. 8.2.15

  - type: input
    id: mysql_version
    attributes:
      label: MySQL / MariaDB version
      placeholder: e.g. MariaDB 10.6

  - type: input
    id: browser
    attributes:
      label: Browser used to access ORSEE / Desktop or Mobile
      placeholder: e.g. Chrome 122 (Desktop)
